1])
										
				self.prev = now
			except Exception as err	:
				self.error = True
			await core.wait(100)
	


